### ISSUE TITLE
[Question] issue installing through pip

### ISSUE THREAD

**Issue by jdosio** [bozzlab/pyacoustics-stc#2]
seems to be an issue with the setup.py egg_info not quite sure on the solution.

`%pip install pyacoustics-stc==0.3.0
Collecting pyacoustics-stc==0.3.0
  Using cached pyacoustics_stc-0.3.0-py3-none-any.whl (6.0 kB)
Collecting matplotlib==2.2.2
  Using cached matplotlib-2.2.2.tar.gz (37.3 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\XXXX\AppData\Local\Temp\pip-install-yrbalca_\matplotlib_32f41768f2d04b0fba25ba353c92446c\setup.py", line 43, in <module>
      import setupext
  ModuleNotFoundError: No module named 'setupext'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by bozzlab** [comment]
Hi @jdosio

Sorry for the late reply, 

Could you please provide more details?
1) pip version?
2) python version?
3) What kind of env you used? e.g. `pipenv`, `virtualenv`, `poetry`

However, You could create isolate python environment using `pipenv` or `poetry`.  To avoid conflict of package dependencies. 
`pyacoustics-stc` is required `python version >=3.6` and `matplotlib == 2.2.2`

**Comment by bozzlab** [comment]
I think the root cause of this issue. Could be came from `matplotlib`. Which the version doesn't up to date and also `pyacoustics-stc` still support python version `3.6, 3.7.`  
It might be confilct on installed package dependencies and python version.

Let's check new version of `pyaoucstics-stc`  (v0.4.0)
https://github.com/bozzlab/pyacoustics-stc/releases/tag/v0.4.0

**Comment by ZekDtonik** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
glebino, @devgru-3-2, @OmkarBrahmbhatt, @Wangwei0223, @tfwansh, @sirilux191, @matagus, @randomshana1, @jwarmuz99, @xuesen, @AshrafMd-1, @AversonCoder, @GaganaMD, @par123th, @mgp25, @mysteris, @alexfarfel, @z10011, @Techstudent17, @gofullthrottle, @xoxoiindy, @syedsohan, @Alchemyst0x, @jamesmarkosborne, @ngmisl, @Diogo333, @justinilyes, @gladpieland, @krisguo, @LUOJIUzxy, @KyRionY, @3sarojbhattarai, @pranavprakashkj, @harshagarwal7272, @aycandv, @miz2miz, @guillermodulce, @JAlcocerT, @bashalla, @5rolltacos, @Sajjad-Khoshdooni, @akhilmantha, @brnoleal, @0xmarcusb, @sohamxz, @niteshmodi, @AnthonyMadia, @K4RTH1CC, @Dmdv, @RayhanHamadapranav280300, @strongfist, @Steiner-254, @bengituser, @efffii19, @MarceauKa, @Umarmuhd, @Vinashu, @bukalord99, @SenHanami, @amirifard, @mchlcrtz, @burtchina, @Bbasche, @auleki, @m-lipnican, @KinofRikin, @Honor697, @calongtong, @Devid2005, @KB-perByte, @chetan-2002, @N25sec, @BTHoneyBadger, @marcelbonfim, @realstevenpowell, @funingwang-ht, @GkcA, @wsly1994, @yono-liu, @colonnezi, @anavarani, @Ryugengo, @balpa, @lonelyWarrior127, @cjhaddad, @thisishonext, @nathanscott7, @sheepsheild, @ShihabUddinAhmed, @rxzzh, @anandrajbaghel, @Moinuddin9777, @phborba, @maxbalabay, @AmonCheruiyotHQ, @Dave-Guangyao-Li, @gauravchandrakar25, @hivoon, @iagapov

**Comment by anishmansuri** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Marc-Antoinz, @HydraJedi, @jspw, @obsfx, @mitchellwillocks, @yanmhlv, @keramiozsoy, @deep-nl, @cole67, @truelv, @isecren, @iezed, @lamlephamngoc, @x0oo11235oo0x, @skill-issue0, @CorradoRossi, @YaakovHatam, @samhuang, @santihugin, @lawweiliang, @tenfinney, @ujjwalsingh12, @chawyehsu, @alex-bormotov, @antklim, @thundb, @htamop, @naijab, @Martin317, @Createreality, @ArkadiuszChorian, @aarnadlr, @toledoal, @quangnv13, @monkmonkeymonk, @happypeter, @byre54, @cosin2077, @noam-zeex, @0xZick, @terrancebryant, @gguimp, @dowlandaiello, @sniperyan, @phoorichet, @viralhysteria, @marcusvbrangel, @Neo42, @yannickboog, @eykrehbeinjqadrad, @keyneom, @shrink0r, @esidate, @javalovelinux, @ishouty, @psyshe, @kerokerogeorge, @leonlehmann, @samyogdhital, @danuskatran, @aldorl, @Frac7, @rndlr96, @jkcomment, @mxcoder, @broyson, @RickGray, @zachwinter, @pzalep1, @kovalur, @qiohm, @jiachengxu, @yodalk, @MantisClone, @ftsmax, @shredding, @bhgomes, @franazo, @kirecek, @C91CBQ, @danielefavi, @bws9000, @bahmanbs, @JuanChristopher001, @AndrianBalanescu, @hnhychlcool2, @molekilla, @jawang94, @mohan-1990, @sammdec, @Durgarao310, @svenpeeters, @2oo, @jschoi126, @thisisvinodpatel, @ashim-kr-saha, @Humaather, @qu0b, @pm1122

**Comment by aviddv1** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
grace-mickey405, @van0303, @marshallrichards, @lucebert, @yv, @xgocn, @chkfail, @Comosaycomosah, @mow20, @oshea007, @AlienKevin, @fynch3r, @SteveNjine, @m4n3z40, @cooperinnovativeanalytics, @Ufakeimdope, @fersilva16, @roxaxis, @Rob287, @GuipengLiao, @hey-ynot, @myamout, @0xPacman, @plv, @Odilio, @GanB, @qdriven, @dushaobindoudou, @olriko, @JueShanCoder, @LegendLeo, @goodcopybruh, @joshuazhao-crypto, @dpa85, @Keshia1980, @helderavila, @suryaSivaprakash, @add-le, @ferconde87, @YahikoTendo, @tusharbihani, @zephyrus21, @benny-conn, @ak4ftw, @daniel3303, @caomingpei, @huji0624, @nacim84, @breim, @askenderljf1834, @sraj50, @joe11051105, @ryan0217, @balajmarius, @gmf001, @bachtran, @luzhenqian, @Fonsori, @dave-b-code, @engahmed1190, @askemeline, @seasonHxy, @naderk13, @tkiryc, @sug0, @sodiqmakinde, @wolfflow, @ryandotsmith, @SheenyMeg, @volodymyrprokopyuk, @AnasAlsaqqa, @Kg-pn12, @lostoy0, @madurmanov, @heaventear, @rodleviton, @belikovdev, @njmaeff, @Kdark420, @luo4lu, @dantech0xff, @sheepc, @pupragnarok, @bob6664569, @fribeiro1, @Comosaycomosah, @curtailment, @shunkakinoki, @chopfitzroy, @surgit, @katsew, @eddyvalverde, @Pokkuru, @slavakurilyak, @BlueskyFR, @AleNarder, @mph-code, @HeinzVahlbruch, @ratrevorrow

**Comment by mariusgherasie** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
monochrome-jr, @thanit456, @dreammaster38, @derFBeste, @wlad, @turbospaces, @kevinchensr, @Asienwald, @3ziek, @jschoi126, @Hokore-Dev, @xonixx, @BestNathan, @datgrog, @wisereason100, @takeakiyamasaki, @batukan, @ghaedi1993, @huri000, @DevJihwan, @akimabs, @dangerousbeans, @wtyi, @Abnalhadad, @baiyunping333, @semvtuijn, @mschipperheyn, @imjm8, @Mrscyimsofly, @ahmedahmedov, @ScientiaCapital, @essn, @digitalrbnz, @gyyyy, @HubCodes, @sinao-dev, @data-miner00, @raw34, @coopbri, @ruppysuppy, @scwall, @mustafaassaad, @InuCash, @zezhehh, @guotielong, @lnky79, @vleushin, @wqbill, @smhmayboudi, @peng1027AloisCRR, @stephancill, @jaakjuu1, @Wanderluckas, @nirupamkumar, @ethfun, @kodjunkie, @akbariyansyah, @hwccxyz, @rranjan14, @alexkubica, @gregbyte, @suryasingh, @flwmholtz, @ShaunLWM, @alberts, @sartimo, @billmi, @felipsoarez, @mf1024, @christophercelaya, @rlwns012, @bleib1dj, @jspw, @kajumito, @ft-john, @Guidosalimbeni, @saqlain1020, @kantmakm, @cryptoadu, @ngaoesports, @lyciumlee, @SHAKOTN, @RudeCane, @funkybase, @koladev32, @mehmetboraezer, @GSuleh, @digital-stoic, @Teslow, @pancudaniel7, @web3senior, @atav32, @nicolasmvidal, @0xt3j4s, @ChickenMustNotDie, @vecpeng, @mauro3005, @aaaozay, @LeslieOA
